<a href="https://colab.research.google.com/github/Ganapathi-tech/python-programming/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# Traditional way --- array()

# Homogeneous data  -- ONES(),ZEROS() 

# Diagonal -- EYE(), IDENTITY

# Numerical -- ARANGE(), LINSPACE()

#RANDOM NUMBERS -- RANDOM.RAND(), RANDOM.RANDINT(), RANDOM. RANDN()

In [ ]:
list1 = [10,20,30,40]
np1 = np.array(list1)
print(np1)
print(type(np1))

[10 20 30 40]
<class 'numpy.ndarray'>


In [ ]:
np1.ndim

1

In [ ]:
np1.size

4

In [ ]:
np1.shape

(4,)

In [ ]:
np1.dtype

dtype('int64')

In [ ]:
np1.itemsize

8

In [ ]:
#HOMOGENEOUS DATA ARRAY

In [ ]:
np_zeros = np.zeros((3,4))

In [ ]:
print(np_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
np.zeros((3,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np3 = np.zeros((2,4,5),dtype = int)

In [ ]:
print(np3)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [ ]:
np3[0]

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np3[1]

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np4 = np.zeros((2,3,4,5))

In [ ]:
np4

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [ ]:
np_ones = np.ones((4,5))

In [ ]:
print(np_ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
np_ones4 = np.ones((3,2,2,8), dtype = int)

In [ ]:
np_ones4

array([[[[   1,    1,    1,    1,    1,    1,    1,    1],
         [   1,    1,    1,    1,    1,    1,    1,    1]],

        [[   1,    1,    1, 2222,    1,    1,    1,    1],
         [   1,    1,    1,    1,    1,    1,    1,    1]]],


       [[[   1,    1,    1,    1,    1,    1,    1,    1],
         [   1,    1,    1,    1,    1,    1,    1,    1]],

        [[   1,    1,    1,    1,    1,    1,    1,    1],
         [   1,    1,    1,    1,    1,    1,    1,    1]]],


       [[[   1,    1,    1,    1,    1,    1,    1,    1],
         [   1,    1,    1,    1,    1,    1,    1,    1]],

        [[   1,    1,    1,    1,    1,    1,    1,    1],
         [   1,    1,    1,    1,    1,    1,    1,    1]]]])

In [ ]:
np_ones4[0][1][0][3] = 2222

In [ ]:
# Diagonal 



In [ ]:
dia1 = np.eye(4,4)

In [ ]:
dia1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
dia3 = np.eye(8,8)

In [ ]:
dia3

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
dia4 = np.eye(8,k = -3)

In [ ]:
dia4

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.]])

In [ ]:
dia5 = np.eye(4,5)

In [ ]:
dia5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
ar1 = np.arange(10)

In [ ]:
print(ar1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
ar2 = np.arange(10,30,2)

In [ ]:
ar2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
ar2 = np.arange(11,1,-1)

In [ ]:
ar2

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2])

In [ ]:
np.arange(10, 20, 1.5)

array([10. , 11.5, 13. , 14.5, 16. , 17.5, 19. ])

In [ ]:
list(range(10,20,1.5))

TypeError: ignored

In [ ]:
np.arange(10,20,2, dtype = float)

array([10., 12., 14., 16., 18.])

In [ ]:
np.arange(-8, -2, 2)

array([-8, -6, -4])

In [ ]:
np.arange(1.1, 10.5, 1.1)

array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])

In [ ]:
np2 = np.arange(1,10,1)

In [ ]:
np2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np2.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np2 = np.arange(1,10,1).reshape(3,3)

In [ ]:
np2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(1,10,1).reshape(3,4)

ValueError: ignored

In [ ]:
# linspace

In [ ]:
# arange(start, stop, step)    (1, 10, 2)
# linspace(start, stop, num)  (1,10,2000)

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
lin1 = np.linspace(1,2)

In [ ]:
lin1

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [ ]:
lin1.size

50

In [ ]:
rad1 = np.random.rand(4,5)

In [ ]:
print(rad1)

[[0.22952168 0.32169513 0.95276808 0.17578672 0.65936783]
 [0.69428159 0.92167796 0.75549551 0.55775521 0.00320404]
 [0.60994997 0.23436711 0.08446165 0.52411705 0.37265274]
 [0.40580489 0.91164963 0.43810291 0.92827051 0.05318745]]


In [ ]:
radn1 = np.random.randn(4,5)

In [ ]:
radn1

array([[ 0.53182904,  0.05035281, -2.25208496, -0.52056261,  1.19704716],
       [ 1.2525558 ,  0.6737155 ,  0.81455837, -1.57281156, -1.87127397],
       [ 0.76222768,  0.50750786,  0.25027111,  0.08718143,  0.54200117],
       [-0.41708241,  0.1094482 , -0.6814079 ,  0.75305078,  2.43845067]])

In [ ]:
rint = np.random.randint(10,20,(3,5))

In [ ]:
rint

array([[15, 15, 14, 16, 14],
       [15, 15, 13, 12, 11],
       [15, 15, 19, 10, 12]])

In [ ]:
rint2 = np.random.randint(11.5,22.5,(4,7))

In [ ]:
rint2

array([[13, 14, 11, 13, 11, 14, 21],
       [20, 12, 11, 19, 16, 15, 18],
       [15, 19, 14, 12, 12, 15, 14],
       [17, 14, 15, 19, 16, 13, 15]])

In [ ]:
rint3 = np.random.randint(10,15,(4,5))

In [ ]:
rint3

array([[14, 14, 13, 14, 14],
       [12, 14, 14, 14, 10],
       [12, 12, 12, 12, 11],
       [12, 14, 10, 14, 14]])

In [ ]:
list1 = [100,200,300,400,500]
np.random.choice(list1, (4,5), p= (0.5,0.3,0.0,0.2,0.0))

array([[100, 100, 100, 400, 200],
       [100, 200, 100, 400, 100],
       [100, 400, 100, 100, 200],
       [100, 200, 200, 100, 100]])

In [ ]:
# 1) less memory
# 2) very fast
# 3) convinient

In [ ]:
a = 10000

n1 = np.arange(a)
n2 = np.arange(a)



In [ ]:
l1 = range(a)
l2 = range(a)

In [ ]:
len(l1)

10000

In [ ]:
import sys

In [ ]:
sys.getsizeof(5) * len(l1)

280000

In [ ]:
n1.size

10000

In [ ]:
n1.itemsize * n1.size

80000

In [ ]:
l1

range(0, 10000)

In [ ]:
l2

range(0, 10000)

In [ ]:
import time
a = 100000
l1 = range(a)
l2 = range(a)
s = time.time()
list1=[]
for i,j in zip(l1, l2):
  list1.append(i+j)
e = time.time()
print("Time taken : ", (e - s)*10000)

Time taken :  287.7926826477051


In [ ]:
import time
a = 100000
n1 = np.arange(a)
n2 = np.arange(a)

s = time.time()
n3 = n1 + n2
e = time.time()
print("Time taken : ", (e - s)*10000)

Time taken :  1.8286705017089844


In [ ]:
n3

array([     0,      2,      4, ..., 199994, 199996, 199998])

In [ ]:
list1