<a href="https://colab.research.google.com/github/Ganapathi-tech/python-programming/blob/main/Numpy6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
ary1 = np.random.randint(1,6,(2,2))
ary2 = np.random.randint(1,6,(2,2))

In [ ]:
print(ary1.shape)
print(ary2.shape)

(2, 2)
(2, 2)


In [ ]:
print(ary1)

[[2 4]
 [5 2]]


In [ ]:
print(ary2)

[[2 1]
 [4 5]]


In [ ]:
ary1 + ary2

array([[4, 5],
       [9, 7]])

In [ ]:
np.add(ary1, ary2)

array([[4, 5],
       [9, 7]])

In [ ]:
ary1 - ary2

array([[ 0,  3],
       [ 1, -3]])

In [ ]:
np.subtract(ary1, ary2)

array([[ 0,  3],
       [ 1, -3]])

In [ ]:
ary1* ary2

array([[ 4,  4],
       [20, 10]])

In [ ]:
np.multiply(ary1, ary2)

array([[ 4,  4],
       [20, 10]])

In [ ]:
np.dot(ary1, ary2)

array([[20, 22],
       [18, 15]])

In [ ]:
ary1 / ary2

array([[1.  , 4.  ],
       [1.25, 0.4 ]])

In [ ]:
np.divide(ary1, ary2)

array([[1.  , 4.  ],
       [1.25, 0.4 ]])

In [ ]:
ary1 % ary2

array([[0, 0],
       [1, 2]])

In [ ]:
np.mod(ary1, ary2)

array([[0, 0],
       [1, 2]])

In [ ]:
ary1 ** ary2

array([[  4,   4],
       [625,  32]])

In [ ]:
np.power(ary1, ary2)

array([[  4,   4],
       [625,  32]])

In [ ]:
ary1

array([[2, 4],
       [5, 2]])

In [ ]:
ary1 + 5

array([[ 7,  9],
       [10,  7]])

In [ ]:
np.add(ary1, 5)

array([[ 7,  9],
       [10,  7]])

In [ ]:
n1 = np.random.randint(1,9,(3,5))
n2 = np.random.randint(1,11,(4,3))

In [ ]:
n1

array([[3, 8, 1, 2, 5],
       [7, 7, 1, 4, 7],
       [4, 2, 8, 3, 4]])

In [ ]:
n2

array([[ 8,  3, 10],
       [ 5,  6,  9],
       [ 5,  2,  9],
       [ 2,  9,  6]])

In [ ]:
n1.ndim

2

In [ ]:
n2.ndim

2

In [ ]:
n1.shape

(3, 5)

In [ ]:
n2.shape

(4, 3)

In [ ]:
n1 + n2

ValueError: ignored

In [ ]:
n1 = np.random.randint(1,9,(3,5))
n2 = np.random.randint(1,11,(3,1))

In [ ]:
print(n1.ndim)
print(n1.shape)

2
(3, 5)


In [ ]:
print(n2.ndim)
print(n2.shape)

2
(3, 1)


In [ ]:
n1 + n2

array([[14, 10, 16, 12,  9],
       [ 9,  6, 13, 11,  6],
       [11,  8, 11, 13, 14]])

In [ ]:
np1 = np.random.randint(10,20,(2,4,5))
np2 = np.random.randint(15,30,(4,1))

In [ ]:
np1.shape

(2, 4, 5)

In [ ]:
np1.ndim

3

In [ ]:
np2.shape

(4, 1)

In [ ]:
np2.ndim

2

In [ ]:
np1 + np2

array([[[37, 30, 31, 34, 36],
        [36, 39, 45, 42, 45],
        [29, 35, 29, 37, 38],
        [45, 46, 46, 43, 41]],

       [[35, 32, 32, 30, 37],
        [42, 43, 38, 45, 41],
        [33, 38, 38, 32, 36],
        [37, 41, 41, 43, 45]]])

In [ ]:
ary1 = np.array([[11,22],[10,20]])

In [ ]:
type(ary1)

numpy.ndarray

In [ ]:
print(ary1
      )

[[11 22]
 [10 20]]


In [ ]:
mat1 = np.matrix([[11,22],[10,20]])

In [ ]:
print(mat1)

[[11 22]
 [10 20]]


In [ ]:
type(mat1)

numpy.matrix

In [ ]:
mat1 = np.matrix("9,18;3,6")
mat2 = np.matrix([[1,2],[3,4]])

In [ ]:
mat1

matrix([[ 9, 18],
        [ 3,  6]])

In [ ]:
np1 = np.matrix("9,18,8;3,6,9;1,2,3")

In [ ]:
np1

matrix([[ 9, 18,  8],
        [ 3,  6,  9],
        [ 1,  2,  3]])

In [ ]:
mat1

matrix([[ 9, 18],
        [ 3,  6]])

In [ ]:
mat2

matrix([[1, 2],
        [3, 4]])

In [ ]:
mat1 + mat2

matrix([[10, 20],
        [ 6, 10]])

In [ ]:
mat1* mat2

matrix([[63, 90],
        [21, 30]])

In [ ]:
# Determinent 
# Inverse
# power
# linear equation

In [ ]:
mat5 = np.matrix("1,2;3,4")

In [ ]:
mat5

matrix([[1, 2],
        [3, 4]])

In [ ]:
a = np.linalg.det(mat5)
round(a)

-2

In [ ]:
mat33 = np.matrix("1,2,3;2,3,4;1,4,2")

In [ ]:
mat33

matrix([[1, 2, 3],
        [2, 3, 4],
        [1, 4, 2]])

In [ ]:
b = np.linalg.det(mat33)
round(b)

5

In [ ]:
matx = np.matrix("1,2;3,4")

In [ ]:
matx

matrix([[1, 2],
        [3, 4]])

In [ ]:
np.linalg.inv(matx)

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [ ]:
np.linalg.matrix_power(matx,-1) 

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [ ]:
matx*matx

matrix([[ 7, 10],
        [15, 22]])

In [ ]:
a = np.array([[3,1],[1,2]])

In [ ]:
b = np.array([9,8])

In [ ]:
np.linalg.solve(a,b)

array([2., 3.])

In [ ]:
x =np.array([[6,2,-5],[3,3,-2],[7,5,-3]])

In [ ]:
y = np.array([13,13,16])

In [ ]:
np.linalg.solve(x,y)

array([-2.23076923,  4.15384615, -3.61538462])