<a href="https://colab.research.google.com/github/Ganapathi-tech/python-programming/blob/main/numpy4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
ary1 = np.random.randint(10,30,(3,4,6))
ary1

array([[[21, 13, 14, 21, 19, 12],
        [11, 20, 12, 10, 29, 17],
        [21, 13, 27, 20, 18, 27],
        [14, 13, 28, 26, 15, 23]],

       [[28, 22, 28, 23, 27, 21],
        [20, 10, 25, 16, 20, 23],
        [21, 22, 29, 29, 17, 28],
        [13, 29, 23, 14, 10, 20]],

       [[21, 19, 10, 18, 13, 18],
        [18, 14, 13, 28, 12, 12],
        [17, 13, 29, 26, 13, 22],
        [28, 16, 25, 13, 19, 21]]])

In [ ]:
ary1[0:2:1,1:3:1 , 1:4:1    ]

array([[[11, 19, 12],
        [25, 24, 18]],

       [[28, 12, 29],
        [10, 17, 24]]])

In [ ]:
ary1

array([[[21, 13, 14, 21, 19, 12],
        [11, 20, 12, 10, 29, 17],
        [21, 13, 27, 20, 18, 27],
        [14, 13, 28, 26, 15, 23]],

       [[28, 22, 28, 23, 27, 21],
        [20, 10, 25, 16, 20, 23],
        [21, 22, 29, 29, 17, 28],
        [13, 29, 23, 14, 10, 20]],

       [[21, 19, 10, 18, 13, 18],
        [18, 14, 13, 28, 12, 12],
        [17, 13, 29, 26, 13, 22],
        [28, 16, 25, 13, 19, 21]]])

In [ ]:
ary1[  0 : 3 : 2   , 1:3:1     , 0: 3 : 1        ]

array([[[11, 20, 12],
        [21, 13, 27]],

       [[18, 14, 13],
        [17, 13, 29]]])

In [ ]:
np1 = np.arange(11,31)

In [ ]:
np1

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [ ]:
np1.size

20

In [ ]:
np1 = np1.reshape(4,5)

In [ ]:
np1

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
np1

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [ ]:
np1.size

20

In [ ]:
np1.reshape(2,10)

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [ ]:
np1.reshape(2,2,5)

array([[[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

In [ ]:
np1.reshape(3,4,5)

ValueError: ignored

In [ ]:
# resize

In [ ]:
np1

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [ ]:
np1.resize(4,5)

In [ ]:
np1

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
np2 = np.arange(15,31)

In [ ]:
np2

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
np2.size

16

In [ ]:
np2.resize(2,2,4)

In [ ]:
np2

array([[[15, 16, 17, 18],
        [19, 20, 21, 22]],

       [[23, 24, 25, 26],
        [27, 28, 29, 30]]])

In [ ]:
np2

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
np2.size

16

In [ ]:
np2.resize(4,5, refcheck=False)

In [ ]:
np2

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30,  0,  0,  0,  0]])

In [ ]:
np3 = np.arange(15,50)

In [ ]:
np3.size

35

In [ ]:
np3.resize((3,4,5),refcheck = False)

In [ ]:
np3

array([[[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [ 0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]]])

In [ ]:
np4 = np.arange(10,25)

In [ ]:
np4.size

15

In [ ]:
np4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
np4 = np.resize(np4,(4,6))

In [ ]:
np4

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [ ]:
np4

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [ ]:
np4.shape

(4, 6)

In [ ]:
np4.size

24

In [ ]:
np5 = np4.transpose()

In [ ]:
np5

array([[10, 16, 22, 13],
       [11, 17, 23, 14],
       [12, 18, 24, 15],
       [13, 19, 10, 16],
       [14, 20, 11, 17],
       [15, 21, 12, 18]])

In [ ]:
np5.shape

(6, 4)

In [ ]:
np3

array([[[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [ 0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]]])

In [ ]:
np3.shape

(3, 4, 5)

In [ ]:
tnp3 = np3.transpose()

In [ ]:
tnp3

array([[[15, 35,  0],
        [20, 40,  0],
        [25, 45,  0],
        [30,  0,  0]],

       [[16, 36,  0],
        [21, 41,  0],
        [26, 46,  0],
        [31,  0,  0]],

       [[17, 37,  0],
        [22, 42,  0],
        [27, 47,  0],
        [32,  0,  0]],

       [[18, 38,  0],
        [23, 43,  0],
        [28, 48,  0],
        [33,  0,  0]],

       [[19, 39,  0],
        [24, 44,  0],
        [29, 49,  0],
        [34,  0,  0]]])

In [ ]:
tnp3.shape

(5, 4, 3)

In [ ]:
np1

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
ary2 = np.arange(1, 10)

In [ ]:
ary2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ary2.transpose()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ary1

array([[[21, 13, 14, 21, 19, 12],
        [11, 20, 12, 10, 29, 17],
        [21, 13, 27, 20, 18, 27],
        [14, 13, 28, 26, 15, 23]],

       [[28, 22, 28, 23, 27, 21],
        [20, 10, 25, 16, 20, 23],
        [21, 22, 29, 29, 17, 28],
        [13, 29, 23, 14, 10, 20]],

       [[21, 19, 10, 18, 13, 18],
        [18, 14, 13, 28, 12, 12],
        [17, 13, 29, 26, 13, 22],
        [28, 16, 25, 13, 19, 21]]])

In [ ]:
ary1.shape

(3, 4, 6)

In [ ]:
ary1.transpose().shape

(6, 4, 3)

In [ ]:
ary3 = ary1.transpose((1,2,0))

In [ ]:
ary3

array([[[21, 28, 21],
        [13, 22, 19],
        [14, 28, 10],
        [21, 23, 18],
        [19, 27, 13],
        [12, 21, 18]],

       [[11, 20, 18],
        [20, 10, 14],
        [12, 25, 13],
        [10, 16, 28],
        [29, 20, 12],
        [17, 23, 12]],

       [[21, 21, 17],
        [13, 22, 13],
        [27, 29, 29],
        [20, 29, 26],
        [18, 17, 13],
        [27, 28, 22]],

       [[14, 13, 28],
        [13, 29, 16],
        [28, 23, 25],
        [26, 14, 13],
        [15, 10, 19],
        [23, 20, 21]]])

In [ ]:
ary3.shape

(4, 6, 3)

In [ ]:

np2

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30,  0,  0,  0,  0]])

In [ ]:
np2.shape

(4, 5)

In [ ]:
np22 = np.swapaxes(np2,1,0)

In [ ]:
np22.shape

(5, 4)

In [ ]:
ary3

array([[[21, 28, 21],
        [13, 22, 19],
        [14, 28, 10],
        [21, 23, 18],
        [19, 27, 13],
        [12, 21, 18]],

       [[11, 20, 18],
        [20, 10, 14],
        [12, 25, 13],
        [10, 16, 28],
        [29, 20, 12],
        [17, 23, 12]],

       [[21, 21, 17],
        [13, 22, 13],
        [27, 29, 29],
        [20, 29, 26],
        [18, 17, 13],
        [27, 28, 22]],

       [[14, 13, 28],
        [13, 29, 16],
        [28, 23, 25],
        [26, 14, 13],
        [15, 10, 19],
        [23, 20, 21]]])

In [ ]:
ary3.shape

(4, 6, 3)

In [ ]:
ary3.swapaxes(2,0)

array([[[21, 11, 21, 14],
        [13, 20, 13, 13],
        [14, 12, 27, 28],
        [21, 10, 20, 26],
        [19, 29, 18, 15],
        [12, 17, 27, 23]],

       [[28, 20, 21, 13],
        [22, 10, 22, 29],
        [28, 25, 29, 23],
        [23, 16, 29, 14],
        [27, 20, 17, 10],
        [21, 23, 28, 20]],

       [[21, 18, 17, 28],
        [19, 14, 13, 16],
        [10, 13, 29, 25],
        [18, 28, 26, 13],
        [13, 12, 13, 19],
        [18, 12, 22, 21]]])

In [ ]:
ary1

array([[[21, 13, 14, 21, 19, 12],
        [11, 20, 12, 10, 29, 17],
        [21, 13, 27, 20, 18, 27],
        [14, 13, 28, 26, 15, 23]],

       [[28, 22, 28, 23, 27, 21],
        [20, 10, 25, 16, 20, 23],
        [21, 22, 29, 29, 17, 28],
        [13, 29, 23, 14, 10, 20]],

       [[21, 19, 10, 18, 13, 18],
        [18, 14, 13, 28, 12, 12],
        [17, 13, 29, 26, 13, 22],
        [28, 16, 25, 13, 19, 21]]])

In [ ]:
ary1.flatten()

array([21, 13, 14, 21, 19, 12, 11, 20, 12, 10, 29, 17, 21, 13, 27, 20, 18,
       27, 14, 13, 28, 26, 15, 23, 28, 22, 28, 23, 27, 21, 20, 10, 25, 16,
       20, 23, 21, 22, 29, 29, 17, 28, 13, 29, 23, 14, 10, 20, 21, 19, 10,
       18, 13, 18, 18, 14, 13, 28, 12, 12, 17, 13, 29, 26, 13, 22, 28, 16,
       25, 13, 19, 21])

In [ ]:
ary1.flatten(order = "C")

array([21, 13, 14, 21, 19, 12, 11, 20, 12, 10, 29, 17, 21, 13, 27, 20, 18,
       27, 14, 13, 28, 26, 15, 23, 28, 22, 28, 23, 27, 21, 20, 10, 25, 16,
       20, 23, 21, 22, 29, 29, 17, 28, 13, 29, 23, 14, 10, 20, 21, 19, 10,
       18, 13, 18, 18, 14, 13, 28, 12, 12, 17, 13, 29, 26, 13, 22, 28, 16,
       25, 13, 19, 21])

In [ ]:
np2

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30,  0,  0,  0,  0]])

In [ ]:
np2.flatten(order =  "C")

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,  0,
        0,  0,  0])

In [ ]:
np2.flatten(order="F")

array([15, 20, 25, 30, 16, 21, 26,  0, 17, 22, 27,  0, 18, 23, 28,  0, 19,
       24, 29,  0])

In [ ]:
ary1

array([[[21, 13, 14, 21, 19, 12],
        [11, 20, 12, 10, 29, 17],
        [21, 13, 27, 20, 18, 27],
        [14, 13, 28, 26, 15, 23]],

       [[28, 22, 28, 23, 27, 21],
        [20, 10, 25, 16, 20, 23],
        [21, 22, 29, 29, 17, 28],
        [13, 29, 23, 14, 10, 20]],

       [[21, 19, 10, 18, 13, 18],
        [18, 14, 13, 28, 12, 12],
        [17, 13, 29, 26, 13, 22],
        [28, 16, 25, 13, 19, 21]]])

In [ ]:
ary1.flatten(order = "c")

In [ ]:
ary1.flatten(order = "F")

array([21, 28, 21, 11, 20, 18, 21, 21, 17, 14, 13, 28, 13, 22, 19, 20, 10,
       14, 13, 22, 13, 13, 29, 16, 14, 28, 10, 12, 25, 13, 27, 29, 29, 28,
       23, 25, 21, 23, 18, 10, 16, 28, 20, 29, 26, 26, 14, 13, 19, 27, 13,
       29, 20, 12, 18, 17, 13, 15, 10, 19, 12, 21, 18, 17, 23, 12, 27, 28,
       22, 23, 20, 21])

In [ ]:
np2

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30,  0,  0,  0,  0]])

In [ ]:
np2.shape

(4, 5)

In [ ]:
import time
for i in np2:
  print(i)
  for j in i:
    print(j)
    time.sleep(1)

[15 16 17 18 19]
15
16
17
18
19
[20 21 22 23 24]
20
21
22
23
24
[25 26 27 28 29]
25
26
27
28
29
[30  0  0  0  0]
30
0
0
0
0


In [ ]:
ary1

array([[[21, 13, 14, 21, 19, 12],
        [11, 20, 12, 10, 29, 17],
        [21, 13, 27, 20, 18, 27],
        [14, 13, 28, 26, 15, 23]],

       [[28, 22, 28, 23, 27, 21],
        [20, 10, 25, 16, 20, 23],
        [21, 22, 29, 29, 17, 28],
        [13, 29, 23, 14, 10, 20]],

       [[21, 19, 10, 18, 13, 18],
        [18, 14, 13, 28, 12, 12],
        [17, 13, 29, 26, 13, 22],
        [28, 16, 25, 13, 19, 21]]])

In [ ]:
for i in ary1:
  print(i)
  print("*******************")
  for j in i :
    print(j)
    time.sleep(1)

[[21 13 14 21 19 12]
 [11 20 12 10 29 17]
 [21 13 27 20 18 27]
 [14 13 28 26 15 23]]
*******************
[21 13 14 21 19 12]
[11 20 12 10 29 17]
[21 13 27 20 18 27]
[14 13 28 26 15 23]
[[28 22 28 23 27 21]
 [20 10 25 16 20 23]
 [21 22 29 29 17 28]
 [13 29 23 14 10 20]]
*******************
[28 22 28 23 27 21]
[20 10 25 16 20 23]
[21 22 29 29 17 28]
[13 29 23 14 10 20]
[[21 19 10 18 13 18]
 [18 14 13 28 12 12]
 [17 13 29 26 13 22]
 [28 16 25 13 19 21]]
*******************
[21 19 10 18 13 18]
[18 14 13 28 12 12]
[17 13 29 26 13 22]
[28 16 25 13 19 21]


In [ ]:
a1 = np.arange(1,6)

In [ ]:
a2 = np.arange(11,16)

In [ ]:
print(a1)
print(a2)

[1 2 3 4 5]
[11 12 13 14 15]


In [ ]:
a1 + a2

array([12, 14, 16, 18, 20])

In [ ]:
a2 - a1

array([10, 10, 10, 10, 10])

In [ ]:
a1*a2

array([11, 24, 39, 56, 75])

In [ ]:
a1 / a2

array([0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333])

In [ ]:
a1

array([1, 2, 3, 4, 5])

In [ ]:
a1 + 5

array([ 6,  7,  8,  9, 10])

In [ ]:
a1 * 5 

array([ 5, 10, 15, 20, 25])

In [ ]:
b2 = np.random.randint(1,5,(3,3))

In [ ]:
b3 = np.random.randint(5,9,(3,3))

In [ ]:
b2

array([[3, 2, 4],
       [4, 2, 3],
       [2, 2, 2]])

In [ ]:
b3

array([[5, 7, 7],
       [5, 7, 6],
       [7, 8, 7]])

In [ ]:
b2.ndim

2

In [ ]:
b3.ndim

2

In [ ]:
b2.shape

(3, 3)

In [ ]:
b3.shape

(3, 3)

In [ ]:
b2 + b3

array([[ 8,  9, 11],
       [ 9,  9,  9],
       [ 9, 10,  9]])

In [ ]:
b2 - b3

array([[-2, -5, -3],
       [-1, -5, -3],
       [-5, -6, -5]])

In [ ]:
b2*b3

array([[15, 14, 28],
       [20, 14, 18],
       [14, 16, 14]])

In [ ]:
b2.dot(b3)

array([[53, 67, 61],
       [51, 66, 61],
       [34, 44, 40]])

In [ ]:
print(b2)
print(b3)

[[3 2 4]
 [4 2 3]
 [2 2 2]]
[[5 7 7]
 [5 7 6]
 [7 8 7]]


In [ ]:
b2

array([[3, 2, 4],
       [4, 2, 3],
       [2, 2, 2]])

In [ ]:
b2 * 5

array([[15, 10, 20],
       [20, 10, 15],
       [10, 10, 10]])

In [ ]:
n1 = np.random.randint(3,9,(3,4))

In [ ]:
n1

array([[8, 7, 7, 4],
       [7, 3, 8, 7],
       [6, 6, 8, 6]])

In [ ]:
n2 = np.random.randint(3,9,(4,3))

In [ ]:
n2

array([[8, 4, 4],
       [8, 8, 8],
       [7, 4, 3],
       [3, 7, 8]])

In [ ]:
n1 + n2

ValueError: ignored

In [ ]:
n3 = np.random.randint(3,9,(3,1))
n4 = np.random.randint(3,9,(3,4))

In [ ]:
n3 + n4

array([[11,  9, 13, 10],
       [11, 12,  9, 12],
       [13, 14, 10, 13]])

In [ ]:
n3

array([[6],
       [5],
       [7]])

In [ ]:
n4

array([[5, 3, 7, 4],
       [6, 7, 4, 7],
       [6, 7, 3, 6]])

In [ ]:
n3.ndim


2

In [ ]:
n4.ndim

2

In [ ]:
n3.shape

(3, 1)

In [ ]:
n4.shape

(3, 4)

In [ ]:
n3 + n4

array([[11,  9, 13, 10],
       [11, 12,  9, 12],
       [13, 14, 10, 13]])

In [ ]:
n5 = np.random.randint(10,20,(4,6))
n6 = np.random.randint(20,30,(4,1))

In [ ]:
n5 + n6

array([[46, 37, 44, 39, 39, 42],
       [43, 46, 37, 41, 42, 42],
       [34, 40, 40, 43, 38, 39],
       [38, 41, 38, 41, 38, 41]])

In [ ]:
ary5 = np.random.randint(10,20,(2,4,6))

In [ ]:
ary5

array([[[12, 17, 13, 16, 11, 16],
        [16, 12, 13, 11, 12, 16],
        [19, 13, 19, 19, 12, 18],
        [16, 17, 16, 18, 10, 19]],

       [[19, 17, 19, 16, 14, 17],
        [16, 10, 16, 15, 11, 10],
        [16, 15, 17, 16, 11, 14],
        [12, 16, 10, 14, 10, 18]]])

In [ ]:
ary6 = np.random.randint(10,20,(4,1))

In [ ]:
ary5 + ary6

array([[[27, 32, 28, 31, 26, 31],
        [28, 24, 25, 23, 24, 28],
        [32, 26, 32, 32, 25, 31],
        [31, 32, 31, 33, 25, 34]],

       [[34, 32, 34, 31, 29, 32],
        [28, 22, 28, 27, 23, 22],
        [29, 28, 30, 29, 24, 27],
        [27, 31, 25, 29, 25, 33]]])

In [ ]:
ary5 * ary6

array([[[180, 255, 195, 240, 165, 240],
        [192, 144, 156, 132, 144, 192],
        [247, 169, 247, 247, 156, 234],
        [240, 255, 240, 270, 150, 285]],

       [[285, 255, 285, 240, 210, 255],
        [192, 120, 192, 180, 132, 120],
        [208, 195, 221, 208, 143, 182],
        [180, 240, 150, 210, 150, 270]]])