<a href="https://colab.research.google.com/github/Ganapathi-tech/python-programming/blob/main/Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np1 = np.arange(11,20)

In [ ]:
print(np1)

[11 12 13 14 15 16 17 18 19]


In [ ]:
np1[5]

16

In [ ]:
np2 = np.random.randint(18, 27, (4,4))

In [ ]:
print(np2)

[[19 25 23 20]
 [19 20 24 23]
 [19 19 20 26]
 [20 26 18 20]]


In [ ]:
np3 = np.random.randint(25,40,(2,4,4))

In [ ]:
print(np3)

[[[39 33 38 35]
  [26 27 33 38]
  [39 26 30 25]
  [28 29 32 37]]

 [[36 35 29 37]
  [39 37 26 34]
  [34 36 28 32]
  [35 34 28 29]]]


In [ ]:
# np3[3rd dim][Rows][Columns]
np3[0][1][2]

33

In [ ]:
np3

array([[[39, 33, 38, 35],
        [26, 27, 33, 38],
        [39, 26, 30, 25],
        [28, 29, 32, 37]],

       [[36, 35, 29, 37],
        [39, 37, 26, 34],
        [34, 36, 28, 32],
        [35, 34, 28, 29]]])

In [ ]:
np3[1][2][1]

36

In [ ]:
np4 = np.random.randint(50,90,(2,3,2,6))

In [ ]:
np4

array([[[[59, 50, 87, 82, 79, 59],
         [75, 84, 72, 50, 69, 59]],

        [[54, 83, 83, 66, 53, 50],
         [66, 88, 87, 54, 61, 84]],

        [[50, 59, 60, 84, 52, 64],
         [64, 74, 74, 63, 76, 56]]],


       [[[61, 87, 69, 51, 83, 52],
         [84, 70, 54, 57, 62, 75]],

        [[72, 53, 77, 63, 63, 89],
         [70, 68, 66, 54, 70, 89]],

        [[83, 57, 57, 60, 71, 73],
         [75, 55, 52, 77, 80, 75]]]])

In [ ]:
np4.shape

(2, 3, 2, 6)

In [ ]:
np4

array([[[[59, 50, 87, 82, 79, 59],
         [75, 84, 72, 50, 69, 59]],

        [[54, 83, 83, 66, 53, 50],
         [66, 88, 87, 54, 61, 84]],

        [[50, 59, 60, 84, 52, 64],
         [64, 74, 74, 63, 76, 56]]],


       [[[61, 87, 69, 51, 83, 52],
         [84, 70, 54, 57, 62, 75]],

        [[72, 53, 77, 63, 63, 89],
         [70, 68, 66, 54, 70, 89]],

        [[83, 57, 57, 60, 71, 73],
         [75, 55, 52, 77, 80, 75]]]])

In [ ]:
np4[0][1][0][0]

54

In [ ]:
np4

array([[[[59, 50, 87, 82, 79, 59],
         [75, 84, 72, 50, 69, 59]],

        [[54, 83, 83, 66, 53, 50],
         [66, 88, 87, 54, 61, 84]],

        [[50, 59, 60, 84, 52, 64],
         [64, 74, 74, 63, 76, 56]]],


       [[[61, 87, 69, 51, 83, 52],
         [84, 70, 54, 57, 62, 75]],

        [[72, 53, 77, 63, 63, 89],
         [70, 68, 66, 54, 70, 89]],

        [[83, 57, 57, 60, 71, 73],
         [75, 55, 52, 77, 80, 75]]]])

In [ ]:
ary4 = np.random.randint(10,30,(2,3,4,4))

In [ ]:
ary4

array([[[[11, 21, 20, 13],
         [28, 24, 25, 12],
         [27, 24, 12, 16],
         [10, 13, 26, 20]],

        [[10, 27, 10, 25],
         [28, 10, 20, 29],
         [20, 29, 16, 22],
         [19, 13, 15, 16]],

        [[21, 11, 28, 25],
         [15, 21, 29, 12],
         [28, 20, 29, 10],
         [14, 23, 11, 12]]],


       [[[23, 24, 24, 19],
         [15, 24, 21, 26],
         [13, 23, 16, 28],
         [21, 20, 15, 17]],

        [[19, 20, 16, 19],
         [15, 20, 23, 10],
         [25, 28, 21, 10],
         [13, 29, 11, 19]],

        [[26, 26, 26, 10],
         [11, 14, 27, 25],
         [26, 23, 11, 11],
         [27, 27, 24, 10]]]])

In [ ]:
ary4[ 0 ][ 2 ][ 1 ][ 2 ]

29

In [ ]:
np2

array([[19, 25, 23, 20],
       [19, 20, 24, 23],
       [19, 19, 20, 26],
       [20, 26, 18, 20]])

In [ ]:
np2.ndim

2

In [ ]:
np2[1][2]

24

In [ ]:
# np2[<Rows>   , <Columns>    ]
np2[1,2]

24

In [ ]:
np2

array([[19, 25, 23, 20],
       [19, 20, 24, 23],
       [19, 19, 20, 26],
       [20, 26, 18, 20]])

In [ ]:
np2[3][1]

26

In [ ]:
np2[3 ,1 ]

26

In [ ]:
# np3[ <3rd Dim>  , <Rows>   , <Columns>   ]
np3

array([[[39, 33, 38, 35],
        [26, 27, 33, 38],
        [39, 26, 30, 25],
        [28, 29, 32, 37]],

       [[36, 35, 29, 37],
        [39, 37, 26, 34],
        [34, 36, 28, 32],
        [35, 34, 28, 29]]])

In [ ]:
np3[0][1][2]

33

In [ ]:
np3[  0      ,     1      ,   2       ]

33

In [ ]:
np1

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
# np1[start : stop : step]
# step = +ve, always starting index < ending index
# step = -ve : always starting index > ending index

np1[2 : 6 : 1]

array([13, 14, 15, 16])

In [ ]:
np2

array([[19, 25, 23, 20],
       [19, 20, 24, 23],
       [19, 19, 20, 26],
       [20, 26, 18, 20]])

In [ ]:
# np2[row][columns]
# np2[<rows> , <columns>]

In [ ]:
np2[1:3:1, : :]

array([[19, 20, 24, 23],
       [19, 19, 20, 26]])

In [ ]:
np2

array([[19, 25, 23, 20],
       [19, 20, 24, 23],
       [19, 19, 20, 26],
       [20, 26, 18, 20]])

In [ ]:
np2[ 1:3:1 , 0:3:1  ]

array([[19, 20, 24],
       [19, 19, 20]])

In [ ]:
ary2 = np.random.randint(25,50,(6,8))

In [ ]:
ary2

array([[28, 28, 43, 42, 48, 34, 30, 27],
       [26, 47, 39, 44, 41, 33, 48, 45],
       [46, 49, 34, 48, 36, 34, 31, 36],
       [44, 49, 49, 41, 27, 45, 47, 45],
       [32, 33, 44, 43, 36, 38, 33, 41],
       [39, 32, 30, 44, 45, 31, 37, 45]])

In [ ]:
ary2.ndim

2

In [ ]:
ary2.size

48

In [ ]:
ary2.shape

(6, 8)

In [ ]:
ary2

array([[28, 28, 43, 42, 48, 34, 30, 27],
       [26, 47, 39, 44, 41, 33, 48, 45],
       [46, 49, 34, 48, 36, 34, 31, 36],
       [44, 49, 49, 41, 27, 45, 47, 45],
       [32, 33, 44, 43, 36, 38, 33, 41],
       [39, 32, 30, 44, 45, 31, 37, 45]])

In [ ]:
ary2[ 1 : 4 : 1  ,    2 : 7 : 1  ]

array([[39, 44, 41, 33, 48],
       [34, 48, 36, 34, 31],
       [49, 41, 27, 45, 47]])

In [ ]:
ary3 = np.random.randint(30,60,(2,4,6))

In [ ]:
print(ary3)

[[[53 43 35 41 34 58]
  [31 54 42 41 34 54]
  [53 37 39 31 32 49]
  [37 45 57 43 48 41]]

 [[57 49 54 33 50 33]
  [43 57 57 43 53 34]
  [31 32 51 57 32 55]
  [59 35 45 50 37 34]]]


In [ ]:
# ary3[][][]
# ary3[  3rd dim  , rows    , columns    ]


In [ ]:
ary3[0 : 1 : 1 ,  0 : 4 : 1   ,   2 : 4:1      ]

array([[[35, 41],
        [42, 41],
        [39, 31],
        [57, 43]]])

In [ ]:
ary3

array([[[53, 43, 35, 41, 34, 58],
        [31, 54, 42, 41, 34, 54],
        [53, 37, 39, 31, 32, 49],
        [37, 45, 57, 43, 48, 41]],

       [[57, 49, 54, 33, 50, 33],
        [43, 57, 57, 43, 53, 34],
        [31, 32, 51, 57, 32, 55],
        [59, 35, 45, 50, 37, 34]]])

In [ ]:
ary3[ 0 : 2 : 1    ,   1 : 4 : 1    , 2 : 5 : 1     ]

array([[[42, 41, 34],
        [39, 31, 32],
        [57, 43, 48]],

       [[57, 43, 53],
        [51, 57, 32],
        [45, 50, 37]]])

In [ ]:
ary33 = np.random.randint(30,60,(3,4,6))

In [ ]:
print(ary33)

[[[54 39 49 54 46 54]
  [32 44 38 50 38 39]
  [37 46 38 37 58 59]
  [49 47 58 43 42 51]]

 [[33 44 40 45 39 50]
  [30 35 58 35 59 49]
  [31 55 53 36 45 36]
  [52 43 31 46 56 39]]

 [[56 40 34 53 32 59]
  [47 47 48 51 33 40]
  [49 46 59 42 39 32]
  [49 52 36 43 50 52]]]


In [ ]:
ary3

array([[[53, 43, 35, 41, 34, 58],
        [31, 54, 42, 41, 34, 54],
        [53, 37, 39, 31, 32, 49],
        [37, 45, 57, 43, 48, 41]],

       [[57, 49, 54, 33, 50, 33],
        [43, 57, 57, 43, 53, 34],
        [31, 32, 51, 57, 32, 55],
        [59, 35, 45, 50, 37, 34]]])

In [ ]:
ary3 > 45

array([[[ True, False, False, False, False,  True],
        [False,  True, False, False, False,  True],
        [ True, False, False, False, False,  True],
        [False, False,  True, False,  True, False]],

       [[ True,  True,  True, False,  True, False],
        [False,  True,  True, False,  True, False],
        [False, False,  True,  True, False,  True],
        [ True, False, False,  True, False, False]]])

In [ ]:
ary3[ary3>45]

array([53, 58, 54, 54, 53, 49, 57, 48, 57, 49, 54, 50, 57, 57, 53, 51, 57,
       55, 59, 50])

In [ ]:
ary33

array([[[54, 39, 49, 54, 46, 54],
        [32, 44, 38, 50, 38, 39],
        [37, 46, 38, 37, 58, 59],
        [49, 47, 58, 43, 42, 51]],

       [[33, 44, 40, 45, 39, 50],
        [30, 35, 58, 35, 59, 49],
        [31, 55, 53, 36, 45, 36],
        [52, 43, 31, 46, 56, 39]],

       [[56, 40, 34, 53, 32, 59],
        [47, 47, 48, 51, 33, 40],
        [49, 46, 59, 42, 39, 32],
        [49, 52, 36, 43, 50, 52]]])

In [ ]:
ary33 > 40

array([[[ True, False,  True,  True,  True,  True],
        [False,  True, False,  True, False, False],
        [False,  True, False, False,  True,  True],
        [ True,  True,  True,  True,  True,  True]],

       [[False,  True, False,  True, False,  True],
        [False, False,  True, False,  True,  True],
        [False,  True,  True, False,  True, False],
        [ True,  True, False,  True,  True, False]],

       [[ True, False, False,  True, False,  True],
        [ True,  True,  True,  True, False, False],
        [ True,  True,  True,  True, False, False],
        [ True,  True, False,  True,  True,  True]]])

In [ ]:
ary33[ ary33 > 40  ]

array([54, 49, 54, 46, 54, 44, 50, 46, 58, 59, 49, 47, 58, 43, 42, 51, 44,
       45, 50, 58, 59, 49, 55, 53, 45, 52, 43, 46, 56, 56, 53, 59, 47, 47,
       48, 51, 49, 46, 59, 42, 49, 52, 43, 50, 52])

In [ ]:
np1

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np1[1:5:1]

array([12, 13, 14, 15])

In [ ]:
np1[1:6:2]

array([12, 14, 16])

In [ ]:
np1[1: 8 : 3]

array([12, 15, 18])

In [ ]:
np1

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
indx = np.array([1,2,4,7,8]) # 1st way

In [ ]:
np1[indx]

array([12, 13, 15, 18, 19])

In [ ]:
np1[[1,2,4,7,8]]  # 2nd way

array([12, 13, 15, 18, 19])

In [ ]:
ary2

array([[28, 28, 43, 42, 48, 34, 30, 27],
       [26, 47, 39, 44, 41, 33, 48, 45],
       [46, 49, 34, 48, 36, 34, 31, 36],
       [44, 49, 49, 41, 27, 45, 47, 45],
       [32, 33, 44, 43, 36, 38, 33, 41],
       [39, 32, 30, 44, 45, 31, 37, 45]])

In [ ]:
# ary2[<rows>][<columns>]
# [1,4,2,0,3],[0,0,1,2,4]      # [1,0][4,0][2,1][0,2][3,4]

ary2[[1,4,2,0,3],[0,0,1,2,4]]

array([26, 32, 49, 43, 27])

In [ ]:
ary3

array([[[53, 43, 35, 41, 34, 58],
        [31, 54, 42, 41, 34, 54],
        [53, 37, 39, 31, 32, 49],
        [37, 45, 57, 43, 48, 41]],

       [[57, 49, 54, 33, 50, 33],
        [43, 57, 57, 43, 53, 34],
        [31, 32, 51, 57, 32, 55],
        [59, 35, 45, 50, 37, 34]]])

In [ ]:
# ary3[3rd dim][rows][columns]
ary3[[0,1,0,1,0,1],[1,2,1,3,2,2],[1,2,3,0,5,4]]

array([54, 51, 41, 59, 49, 32])